[workspace]
members = ["block-producer", "node", "proto", "rpc", "store", "utils"]
resolver = "2"

[workspace.dependencies]
miden-crypto = { package = "miden-crypto", git = "https://github.com/0xPolygonMiden/crypto", branch = "next" }
miden-lib = { package = "miden-lib", git = "https://github.com/keomprotocol/miden-base", branch = "main" }
miden_objects = { package = "miden-objects", git = "https://github.com/keomprotocol/miden-base", branch = "main" }
thiserror = "1.0"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = [
  "fmt",
  "json",
  "env-filter",
] }
